# Generated by Django 4.1.7 on 2023-08-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
